AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Template to deploy the lambda connector in your account.
Resources:
  Function:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: "com.amazonaws.appflow.custom.connector.example.handler.SalesforceLambdaHandler::handleRequest"
      CodeUri: "./target/custom-connector-example-1.0.3.jar"
      Description: "Example for writing and deploying your AppFlow connector"
      Runtime: java8
      Timeout: 30
      MemorySize: 256
      Policies:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Action: 'secretsmanager:GetSecretValue'
          Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:appflow!${AWS::AccountId}-<you-connector-label>-*'
  PolicyPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt Function.Arn
      Action: lambda:InvokeFunction
      Principal: 'appflow.amazonaws.com'
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub 'arn:aws:appflow:${AWS::Region}:${AWS::AccountId}:*'
